### ISSUE TITLE
About parsing MACROS using LibClang

### ISSUE THREAD

**Issue by mannprerak2** [nickmqb/nickmqb.github.io#1]
Hi, I am currently working on [ffigen](https://github.com/dart-lang/ffigen) for the [dart](https://dart.dev/) programming language and wanted to add support for MACROS.

I really liked your approach dealing with MACROS as [you wrote about it here.](https://nickmqb.github.io/2020/01/19/using-libclang-to-generate-c-bindings-for-muon.html#mapping-c-to-muon:~:text=In%20C%2C%20it%20is%20common%20for,is%20assigned%20to%20a%20%E2%80%9Creal%E2%80%9D%20constant.) Can you shed some more light on this approach?

You mention writing additional C code in the form of `const some_type some_temp_name = PREPROCESSOR_CONSTANT;` and then parsing it to evaluate the value of this constant.
I wanted to specifically ask about getting "some_type" w.r.t above statement, is there some additional code involved?

**Comment by nickmqb** [comment]
Hi, the type is determined via a user supplied rules file (see here: https://github.com/nickmqb/muon/blob/d555abd08a90f077eea27c0fb2a33f3ba9c6d2f4/ffigen/main.mu#L277)

It would be nice to not require users to specify this. However, because C macros technically do not have a type, the user may want some control over which Muon type (or Dart type, in your case) is generated (e.g. bit width and sign of integer constant). That said, it may be possible to make a good guess, e.g. automatically detect string constants, though that would require some further digging into libclang to figure out how to get.

Hope this helps!

**Comment by mannprerak2** [comment]
Thanks for replying 😊

I figured out a way actually. We can create an `hpp` file and create constants using the auto keyword.
This type is then automatically resolved by clang.
Something like
```hpp
#define ABC 10
auto abc = ABC; // resolves to int 
```
Evaluating this VarDecl (abc) then gives an EvalResult with the correct type which can then be used for generation.

It would be so much better if libclang had a way to directly evaluate the expression.

**Comment by nickmqb** [comment]
Ah that's a nice solution, I might use that as well in a future version of ffigen :). Agreed that it would be nice if libclang could evaluate (arbitrary) expressions, that could be useful for a wide range of situations.
